Excercise 3-semantic-html
Jaimeandres97/html-tutorial pull request #3
Opened 2020-04-22 00:16 UTC by Jaimeandres97

2020-04-22 01:47 UTC, juancho11gm commented on 3-semantic-html/semantic.html
> +        <meta name="keywords" content="CV, curriculum vitae, learning, job search">
Nice to see these meta tags.

2020-04-22 02:24 UTC, juancho11gm commented on 3-semantic-html/semantic.html
> +            <style>.aligncenter{text-align:right;}</style>
Nice to see you using styles. We are going to see the difference between using `<style>` tag and using `<link rel="stylesheet" href="style.css">` inside the `<head>`
`

2020-04-22 02:24 UTC, juancho11gm commented on 3-semantic-html/semantic.html
> +        </footer>
Please separate the `<address>` of the `<nav>`. You can have both of them inside the `<footer>`, but it's better if you separate them. Something like this: 

```suggestion
<footer>
             <p>You can contact the author here:</p>
            <address>
                <a href="mailto:pushdev.cuentas@gmail.com">pushdev.cuentas@gmail.com</a><br>
                <a href="tel:+13115552368">(311) 555-2368</a>
            </address>
            <p>Content related:</p>
            <nav>
                    <!-- your list items -->
            </nav>
 </footer>
```

2020-04-22 02:27 UTC, juancho11gm requested changes
Good job, I see that you are using the tags that we saw in the session. Please see the comments and send the changes. You can add media type tags like <audio> or the others (if you want). Keep it up!

2020-04-29 01:25 UTC, pushdev-code approved these changes

2020-04-29 01:27 UTC, merged